language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2.100
script:
- dotnet restore
- dotnet build
- dotnet test tests/Application.Tests
notifications:
  email:
  - neil@intapoint.com
deploy:
  provider: azure_web_apps
  verbose: true